aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    max-file-size: ${MAX_FILE_SIZE} # 100MB in bytes

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: co2-analyzer-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true

# application.properties
server.port: 8080

logging:
  level:
    com.example.mlupload: DEBUG
    software.amazon.awssdk: WARN
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
